// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCqcYpQ2VtjbqSoCVUPVRALTp1kSj0fnk',
    appId: '1:836340362776:web:dbba52baadc03e99a0dd6d',
    messagingSenderId: '836340362776',
    projectId: 'thef4turesummit',
    authDomain: 'thef4turesummit.firebaseapp.com',
    storageBucket: 'thef4turesummit.firebasestorage.app',
    measurementId: 'G-TT2MPEVT88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChS1jYZTTmP1wwLa1L-Zej4f8qvJ4zQkQ',
    appId: '1:836340362776:android:a0e12338d230faffa0dd6d',
    messagingSenderId: '836340362776',
    projectId: 'thef4turesummit',
    storageBucket: 'thef4turesummit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgz_5ogzQDEBabGt8AXW8gxK6rsIh_X6w',
    appId: '1:836340362776:ios:f615dee4b5ec8a62a0dd6d',
    messagingSenderId: '836340362776',
    projectId: 'thef4turesummit',
    storageBucket: 'thef4turesummit.firebasestorage.app',
    iosBundleId: 'in.futuresummit.f4ture',
  );
}
